version: '3.9'

services:
  database:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kanban_bot
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres